name: Flatter

on:
  workflow_dispatch:

jobs:
  flatter:
    name: Flatter
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop:23.08
      options: --privileged

    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
      fail-fast: true
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Generate CNAME
        run: |
          echo "flatpak.toastbits.dev" > CNAME

      - name: Install pip
        run: dnf install -y python3-pip

      - name: Install Python packages
        run: pip3 install xmltodict beautifulsoup4 minify-html

      - name: Generate index.html
        run: python3 generatePage.py dev.toastbits ./package ./index.html

      - name: Install Java 17 extension
        run: flatpak install -y flathub org.freedesktop.Sdk.Extension.openjdk17/${{ matrix.arch }}/23.08

      - name: Build (x86_64-only)
        uses: toasterofbread/flatter@main
        if: ${{ matrix.arch == 'x86_64' }}
        with:
          files: |
            package/spmp/dev.toastbits.spmp.yml
          arch: ${{ matrix.arch }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true
          upload-pages-artifact: false

      - name: Build
        uses: toasterofbread/flatter@main
        with:
          files: |
            package/spmp-server/dev.toastbits.spmp-server.yml
          arch: ${{ matrix.arch }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true
          upload-pages-artifact: ${{ matrix.arch == 'aarch64' }}
          upload-pages-includes: |
            CNAME
            index.html
          repo-title: toasterofbread
          repo-url: https://flatpak.toastbits.dev

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: flatter
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
